Repository FRONTENDBOOTCAMP-13th/Vision, pull requests merged in 2025-03, with the labels that each got.

#14 feat : 메인 배너 컴포넌트 작업
  src/components/main-banner.css
  src/components/main-banner.html
Labels: enhancement

#25 Feat/nav
  src/components/nav.css
  src/components/nav.html
Labels: 코드 구현

#27 feat/header 컴포넌트 완성
  src/components/header.css
  src/components/header.html
Labels: 코드 구현

#28 feat : 푸터 컴포넌트 작업
  src/components/footer.css
  src/components/footer.html
Labels: 코드 구현

#31 Feat : recent view 컴포넌트 제작
  index.html
  src/components/recent-view.css
  src/components/recent-view.html
Labels: 코드 구현, 파일 추가

#37 feat : item-info 완료
  src/components/item-info.css
  src/components/item-info.html
Labels: 코드 구현

#42 Feat/event-info
  src/components/event-info.css
  src/components/event-info.html
Labels: 코드 구현

#44 fix : banner 컴포넌트 모바일 반응형 오류 수정
  src/components/main-banner.css
  src/components/sub-banner.css
Labels: 버그 발생, 코드 리팩토링

#45 fix : footer 텍스트 크기 개선
  src/components/footer.css
Labels: 버그 발생, 코드 리팩토링

#46 refactor/nav
  src/components/nav.css
Labels: 코드 리팩토링

#50 init : 이미지 파일 추가
  public/image/item-vertical/vertical-06.webp
  public/image/item-vertical/vertical-07.webp
  public/image/item-vertical/vertical-08.webp
  public/image/item-vertical/vertical-09.webp
  public/image/item-vertical/vertical-10.webp
Labels: 파일 추가

#52 refactor/nav-2
  src/components/nav.css
Labels: 코드 리팩토링

#48 fix : 메인 화면 header&nav 상단 고정
  src/components/header.css
  src/item/main.css
  src/item/main.html
Labels: 버그 발생, 코드 리팩토링

#60 init : index 링크 추가
  index.html
Labels: 코드 구현

#61 feat : pagination component 완료
  public/image/icon/arrow.png
  public/image/icon/double_arrow.png
  src/components/pagination.css
  src/components/pagination.html
Labels: 새로운 기능 추가

#71 feat : list화면에 들어갈 검색창 list-header 완료
  src/components/list-header.css
  src/components/list-header.html
Labels: 코드 구현

#73 feat : list화면에 들어갈 list-filter 컴포넌트 완료 ✔️
  src/components/list-filter.css
  src/components/list-filter.html
Labels: 코드 구현

#72 Feat : list-side-panel 컴포넌트 작업
  public/image/icon/checked.svg
  public/image/icon/default-brand-category.svg
  public/image/icon/selected-brand-category.svg
  public/image/icon/sellected.svg
  public/image/icon/unchecked.svg
  public/image/icon/unsellected.svg
  src/components/list-side-panel.css
  src/components/list-side-panel.html
Labels: 코드 구현, 파일 추가

#77 refactor : nav
  src/components/nav.css
  src/components/nav.html
Labels: 버그 발생, 코드 리팩토링

#80 feat : item-list page Layout 완료
  index.html
  package.json
  public/image/icon/favicon.ico
  src/components/header.css
  src/components/list-header.css
  src/components/section-tab.css
  src/components/section-tab.html
  src/item/item-list.css
  src/item/item-list.html
  src/item/list-item.css
  src/item/list-item.html
  src/style.css
  vite.config.js
Labels: 코드 구현, 파일 추가

#83 bug/main-page
  src/item/main.html
Labels: 코드 리팩토링

#91 Refactor : nav, main 레이아웃 마크업 수정
  src/components/nav.css
  src/item/main.html
Labels: 코드 리팩토링

#93 Refactor : ltem list 레이아웃(2차) 완료
  src/item/item-list.css
  src/item/item-list.html
  src/item/main.css
Labels: 코드 리팩토링

#92 feat : cart-section 컴포넌트 완성 (+ index.html 컴포넌트 링크 연동)
  index.html
  public/image/icon/alarm-checked.svg
  public/image/icon/alarm.svg
  public/image/icon/like-fill.svg
  public/image/icon/like.svg
  src/components/cart-section.css
  src/components/cart-section.html
Labels: 코드 리팩토링, 코드 구현, 파일 추가

#95 Feat : brand-info 컴포넌트 완료
  src/components/brand-info.css
  src/components/brand-info.html
Labels: 코드 구현

#94 Feat : detail-nav 컴포넌트 제작
  src/components/detail-nav.css
  src/components/detail-nav.html
Labels: 코드 구현, 파일 추가

#97 feat : image-datail 폴더 생성, detail-info 컴포넌트 완성
  public/image/item-detail/check-point-wide.png
  public/image/item-detail/check-point.png
  public/image/item-detail/item-pic-wide.png
  public/image/item-detail/item-pic.png
  public/image/item-detail/nutrition-wide.png
  public/image/item-detail/nutrition.png
  src/components/detail-info.css
  src/components/detail-info.html
Labels: 코드 구현, 파일 추가

#100 Refactor : nav 온라인 배경 색 추가
  src/components/nav.css
Labels: 버그 발생, 코드 리팩토링

#101 feat : detail-header 컴포넌트 제작
  src/components/detail-header.css
  src/components/detail-header.html
Labels: 코드 구현

#104 bug : detail-header truncate 적용 이슈 해결
  src/components/detail-header.css
  src/components/detail-header.html
Labels: 버그 발생, 코드 리팩토링

#106 README.md 문서 완성
  README.md
Labels: 문서 업데이트

#109 item-detail 컴포넌트 누락 부분 수정 완료
  src/components/item-detail.css
  src/components/item-detail.html
Labels: 코드 리팩토링, 코드 구현

#110 init : DB용 이미지 파일(review) 업로드
  public/image/item-detail/review-01.webp
  public/image/item-detail/review-02.webp
  public/image/item-detail/review-03.webp
  public/image/item-detail/review-04.webp
Labels: 파일 추가

#107 refactor : item-list 화면 DB 입력 및 이미지 추가
  public/image/item-vertical/vertical-11.webp
  public/image/item-vertical/vertical-12.webp
  public/image/item-vertical/vertical-13.webp
  public/image/item-vertical/vertical-14.webp
  public/image/item-vertical/vertical-15.webp
  public/image/item-vertical/vertical-16.webp
  public/image/item-vertical/vertical-17.webp
  public/image/item-vertical/vertical-18.webp
  public/image/item-vertical/vertical-19.webp
  public/image/item-vertical/vertical-20.webp
  public/image/item-vertical/vertical-21.webp
  public/image/item-vertical/vertical-22.webp
  src/item/item-list.html
Labels: 코드 리팩토링, 코드 구현, 파일 추가

#120 init : item-detail 컴포넌트 index 에 추가
  index.html
Labels: 코드 구현

#122 item-guide 컴포넌트 완성
  src/components/item-guide.css
  src/components/item-guide.html
Labels: 코드 구현

#123 Feat : item-detail 레이아웃 1차 완성
  src/components/cart-section.css
  src/components/detail-header.css
  src/components/detail-info.css
  src/components/detail-nav.css
  src/components/item-detail.css
  src/item/item-detail.css
  src/item/item-detail.html
Labels: 코드 리팩토링, 새로운 기능 추가, 코드 구현

#125 refactor : detail-info(컴포넌트) 코드 수정
  src/components/detail-info.css
Labels: 코드 리팩토링

#126 feat : pagination-arrow 컴포넌트 제작
  src/components/pagination-arrow.css
  src/components/pagination-arrow.html
Labels: 코드 구현

#128 refactor : recent-view 컴포넌트 개선 및 main 페이지 적용
  src/components/recent-view.css
  src/item/main.css
  src/item/main.html
Labels: 버그 발생, 코드 리팩토링

#131 refactor : recent-view 리팩토링
  src/item/item-detail.html
  src/item/item-list.html
  src/item/main.css
Labels: 코드 리팩토링

#140 feat : item-detail 레이아웃 제작
  src/components/item-guide.css
  src/components/item-review.css
  src/item/item-detail.css
  src/item/item-detail.html
Labels: 코드 리팩토링, 코드 구현

#142 init : 고해상도 이미지 추가
  public/image/banner/main-banner-01-wide.webp
  public/image/banner/main-banner-01.webp
  public/image/banner/main-banner-02-wide.webp
  public/image/banner/main-banner-02.webp
  public/image/banner/main-banner-03-wide.webp
  public/image/banner/main-banner-03.webp
  public/image/banner/main-banner-04-wide.webp
  public/image/banner/main-banner-04.webp
  public/image/banner/main-banner-05-wide.webp
  public/image/banner/main-banner-05.webp
  public/image/banner/main-banner-06-wide.webp
  public/image/banner/main-banner-06.webp
  public/image/banner/main-banner-07-wide.webp
  public/image/banner/main-banner-07.webp
  public/image/banner/main-banner-08-wide.webp
  public/image/banner/main-banner-08.webp
  public/image/banner/main-banner-09-wide.webp
  public/image/banner/main-banner-09.webp
  public/image/banner/main-banner-10-wide.webp
  public/image/banner/main-banner-10.webp
  public/image/item-horizontal/horizontal-11.webp
  public/image/item-horizontal/horizontal-12.webp
  public/image/item-horizontal/horizontal-13.webp
  public/image/item-search/item-pic-wide.webp
  public/image/item-search/item-pic.webp
Labels: 파일 추가

#143 feat: nav 카테고리 드롭다운 기능 구현
  src/components/nav.css
  src/components/nav.html
  src/item/main.html
Labels: 코드 리팩토링, 새로운 기능 추가, 코드 구현

#145 fix : item-qna 비밀번호 모달창 위치 변경
  src/components/item-qna.html
  src/item/item-detail.html
Labels: 버그 발생

#146 feat : img-hover-effect 구현 완료
  src/components/item-card.css
Labels: 새로운 기능 추가

#147 refactor : item-list 화면 리팩토링
  src/item/item-list.css
  src/item/item-list.html
Labels: 코드 리팩토링

#158 Refactor : event-info(애니메이션 추가), main(event-info 마크업 수정)
  src/components/event-info.css
  src/components/event-info.html
  src/item/main.css
  src/item/main.html
Labels: 코드 리팩토링, 새로운 기능 추가, 코드 구현

#160 refactor : footer 코드 개선 및 스타일링 수정
  src/components/footer.css
  src/components/footer.html
  src/item/item-detail.html
  src/item/item-list.html
  src/item/main.css
  src/item/main.html
Labels: 코드 리팩토링

#153 feat : item-detail,item-list 마크업 추가
  src/item/item-detail.html
  src/item/item-list.html
Labels: 코드 리팩토링, 코드 구현

#159 refactor : nav 여백, 카테고리 아이콘 컬러 수정
  src/components/nav.css
  src/components/nav.html
Labels: 코드 리팩토링

#162 refactor : main,item-list,item-detail의 nav 마크업 수정(아이콘 컬러 수정)
  src/item/item-detail.html
  src/item/item-list.html
  src/item/main.html
Labels: 코드 리팩토링

#164 feat : nav에서 이동할 페이지 구현 완료(신상품/알뜰쇼핑/특가혜택)
  public/image/item-vertical/vertical-23.webp
  public/image/item-vertical/vertical-24.webp
  public/image/item-vertical/vertical-25.webp
  public/image/promotions/promotions-01-wide.webp
  public/image/promotions/promotions-01.webp
  public/image/promotions/promotions-02-wide.webp
  public/image/promotions/promotions-02.webp
  public/image/promotions/promotions-03-wide.webp
  public/image/promotions/promotions-03.webp
  public/image/promotions/promotions-04-wide.webp
  public/image/promotions/promotions-04.webp
  public/image/promotions/promotions-05-wide.webp
  public/image/promotions/promotions-05.webp
  public/image/promotions/promotions-06-wide.webp
  public/image/promotions/promotions-06.webp
  public/image/promotions/promotions-07-wide.webp
  public/image/promotions/promotions-07.webp
  public/image/promotions/promotions-08-wide.webp
  public/image/promotions/promotions-08.webp
  public/image/promotions/promotions-09-wide.webp
  public/image/promotions/promotions-09.webp
  public/image/promotions/promotions-10-wide.webp
  public/image/promotions/promotions-10.webp
  src/item/item-list-new.html
  src/item/item-list-smart.html
  src/item/promotions.css
  src/item/promotions.html
Labels: 코드 구현

#166 feat : 각 페이지 nav에 링크 연결
  src/item/item-detail.css
  src/item/item-detail.html
  src/item/item-list-new.html
  src/item/item-list-smart.html
  src/item/item-list.css
  src/item/item-list.html
  src/item/main.html
  src/item/promotions.css
  src/item/promotions.html
Labels: 코드 구현

#171 refactor : naming change
  src/item/item-detail.html
  src/item/item-list-new.html
  src/item/item-list-smart.html
  src/item/item-list.html
  src/item/main.html
  src/item/promotions.html
Labels: 코드 구현

#168 feat : item-detail 컴포넌트 Input 요소로 교체
  src/components/item-detail.css
  src/components/item-detail.html
  src/item/item-detail.html
Labels: 코드 리팩토링

#176 refactor : nav 카테고리 tab 키 적용, main 페이지 px -> rem 단위 수정
  src/components/nav.css
  src/components/nav.html
  src/item/main.css
  src/item/main.html
Labels: 코드 리팩토링

#182 refactor : main 페이지 컴포넌트 단위 변경 (px -> rem)
  src/components/event-info.css
  src/components/main-banner.css
  src/components/menu-list.css
  src/components/sub-banner.css
Labels: 코드 리팩토링

#184 fix : 모바일 상단 header padding/위치 조정 완료
  src/components/list-header.css
  src/item/main.css
Labels: 버그 발생

#188 feat : index 페이지 team 컴포넌트 구현
  index.html
  public/image/sanrio/cinnamoroll.webp
  public/image/sanrio/keroppi.webp
  public/image/sanrio/kuromi.png
  public/image/sanrio/pompompurin.webp
  src/index-compoents/team.css
  src/index-compoents/team.html
Labels: 코드 구현

#191 feat : index-card (하단 fix) 구현 완료
  src/index-compoents/index-cards.css
  src/index-compoents/index-cards.html
Labels: 코드 구현

#197 feat : index-link-button 컴포넌트 작업
  index.html
  src/index-compoents/index-nav.css
  src/index-compoents/index-nav.html
Labels: 코드 리팩토링, 코드 구현

#200 Feat : index-our-rules 수정 및 index 전반 레이아웃 조정
  public/image/etc/Frame 259.png
  src/index-compoents/index-link.css
  src/index-compoents/index-nav.html
  src/index-compoents/workflow.css
Labels: 코드 리팩토링, 코드 구현, 파일 추가

#204 refactor : index 스타일링으로 인한 서비스 페이지 오류건 수정
  index.html
  src/style.css
Labels: 버그 발생, 코드 리팩토링
